### ISSUE TITLE
Unable to delete domains

### ISSUE THREAD

**Issue by coderhs** [redpanthers/alexa-keeper#15]
In production after I added the domain. I was unable to remove the domain.

Also can you let me know if, after pressing the delete do we ask for confirmation? Since we are going to be deleting the history when we delete the domain, it would be best if we add that as well.

**Comment by coderhs** [comment]
@sameesh-s & @harisr92 it seems to be limited to ubuntu, chrome. It works in osx, chrome

**Comment by nithinbekal** [comment]
@Nimmyjv Isn't this working now? If so, we can close this.

**Comment by Nimmyjv** [comment]
deleteing domains is working.. no issues

**Comment by nithinbekal** [comment]
@Nimmyjv Ok. Please close this issue.
