### ISSUE TITLE
Website validation and protocol

### ISSUE THREAD

**Issue by nithinbekal** [redpanthers/alexa-keeper#39]
We are currently performing website url validation by checking if the URL contains a dot. This is not a proper way to do this. We should use `URI.parse` for making sure that it is a valid URI.

Before we validate, we should also ensure that the URL contains the protocol. For example, `redpanthers.co` and `http://redpanthers.co` should both be accepted, but we should add the `http://` when it is missing.

```ruby
class Website < AR::Base
  before_validation :add_protocol_to_website

  validates :url, uri: true

  private

  def add_protocol_to_website
    self.url = (self.url[/^http:\/\//] || self.url[/^https:\/\//]) ? self.url : "http://#{self.url}"
  end
end

# app/validators/uri_validator.rb
class UriValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add(attribute, 'is invalid') unless valid_url?(value)
  end

  private

  def valid_uri?(uri)
    URI.parse(uri) && uri.host.present?
  rescue URI::InvalidURIError
    false
  end
end
```

@Nimmyjv You can use the above code for reference, but I haven't tested it, so please make sure I haven't missed out some obvious case.

**Comment by Nimmyjv** [comment]
okay

**Comment by nithinbekal** [comment]
Cleaning up outdated issues/PRs that I created. Feel free to reopen if this is still relevant.
